#!/usr/bin/env bash
# Produce the checked-in v1.20.0 restore fixture on a Docker-capable CI runner.
set -euo pipefail

out=${1:?usage: generate.sh OUTPUT_DIRECTORY}
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

readonly TAG=v1.20.0
readonly BUNDLE_SHA256=77071195f5e8ef07b68a7bde9db20d30c0e64cfb561280d962d555acc03a6d4b
readonly COSIGN_IMAGE=ghcr.io/sigstore/cosign/cosign@sha256:4bedb8de1c5c1abd8dea60de704ba449402d238623fa8bb33d2ccaa9beffcbf5
readonly PASSPHRASE=v120-fixture-passphrase
readonly TARI_WALLET=126J92Yow5y9UoRFd1DNujPmVFq9C1ZeiYWT95UKxz5Y1rzbfjtHg4SCZS1dk83ivzt3m2XRQHTaYUk9SwmyeCvy5BJ
repo=$(git rev-parse --show-toplevel)
wallet=$(
    python3 - "$repo/lib/pithead/25-address-types.sh" <<'PY'
import os, pathlib, sys
source = pathlib.Path(sys.argv[1]).read_text()
code = source.split("import sys\n", 1)[1].split("\nPYEOF", 1)[0].rsplit("raw = b58_decode", 1)[0]
exec(code)
alpha = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
width = {1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 9, 7: 10, 8: 11}
def encode(block):
    n, out = int.from_bytes(block, "big"), []
    for _ in range(width[len(block)]):
        n, remainder = divmod(n, 58)
        out.append(alpha[remainder])
    return "".join(reversed(out))
raw = bytes([18]) + os.urandom(64)
raw += keccak256(raw)[:4]
print("".join(encode(raw[i : i + 8]) for i in range(0, len(raw), 8)))
PY
)

mkdir -p "$out"
base="https://github.com/p2pool-starter-stack/pithead/releases/download/$TAG"
curl -fsSLo "$work/pithead.tar.gz" "$base/pithead.tar.gz"
curl -fsSLo "$work/pithead.tar.gz.sig" "$base/pithead.tar.gz.sig"
printf '%s  %s\n' "$BUNDLE_SHA256" "$work/pithead.tar.gz" | sha256sum -c -
chmod 755 "$work"
chmod 644 "$work/pithead.tar.gz" "$work/pithead.tar.gz.sig"
docker run --rm -e HOME=/tmp -v "$work:/artifact:ro" -v "$repo:/trust:ro" "$COSIGN_IMAGE" \
    verify-blob --key /trust/cosign.pub --signature /artifact/pithead.tar.gz.sig \
    --insecure-ignore-tlog=true /artifact/pithead.tar.gz >/dev/null
tar -xzf "$work/pithead.tar.gz" -C "$work"

cd "$work/pithead"
jq -n --arg wallet "$wallet" --arg tari "$TARI_WALLET" '{
  monero: {mode: "remote", wallet_address: $wallet, node_username: "fixture-rpc-user", node_password: "fixture-rpc-password", remote: {host: "127.0.0.1", rpc_port: 18081, zmq_port: 18083}},
  tari: {mode: "remote", wallet_address: $tari, remote: {host: "127.0.0.1", grpc_port: 18142}},
  p2pool: {pool: "mini", stratum_password: "fixture-stratum-password"},
  dashboard: {auth: {username: "fixture-admin", password: "fixture-dashboard-password"}, onion: {enabled: true, client_auth: true}, control: {enabled: true}, energy: {cost_per_kwh: 0.27, currency: "USD"}}
}' >config.json
printf 'n\n' | ./pithead setup >/dev/null
# v1.20.0's Tor container creates its persisted paths as root.  The fixture owns
# only this disposable checkout, so hand it back before adding the chain sentinel.
sudo chown -R "$(id -u):$(id -g)" data
mkdir -p data/monero data/tari data/p2pool
printf 'v1.20.0 fixture chain data\n' >data/monero/chain-sentinel
PITHEAD_BACKUP_PASSPHRASE="$PASSPHRASE" ./pithead backup --with-chains --yes >/dev/null
install -m 600 backups/*.tar.gz.enc "$out/v1.20.0-backup.tar.gz.enc"
printf '%s\n' "$PASSPHRASE" >"$out/passphrase"
printf '%s\n' "$wallet" >"$out/wallet"
printf '%s\n' 'v1.20.0 signed compose bundle; sha256: 77071195f5e8ef07b68a7bde9db20d30c0e64cfb561280d962d555acc03a6d4b; signature verified against cosign.pub before extraction; disposable remote-node configuration; encrypted backup --with-chains; generated by tests/os/fixtures/v1.20.0/generate.sh' >"$out/PROVENANCE"
