#!/usr/bin/env bash
# Parse representative generated Caddyfiles with the exact Caddy image shipped by Compose.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

if ! docker info >/dev/null 2>&1; then
    echo "SKIP: Docker daemon not available"
    exit 0
fi

CADDY_IMAGE="$(grep -oE 'caddy:[0-9.]+@sha256:[a-f0-9]+' "$ROOT/docker-compose.yml" | head -1)"
[ -n "$CADDY_IMAGE" ] || {
    echo "FAIL: pinned Caddy image not found in docker-compose.yml" >&2
    exit 1
}
CADDY_IMAGE="docker.io/library/$CADDY_IMAGE"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

adapt() { docker run --rm -i "$CADDY_IMAGE" caddy adapt --config - --adapter caddyfile; }

echo "== generated Caddyfiles parse with the shipped Caddy =="

# Prove the parser rejects the directive collision that opened #1037; otherwise the green matrix
# below would establish only that the container command returned zero.
if adapt >"$TMP/invalid.json" 2>/dev/null <<'EOF'; then
https://example.invalid {
    bind 127.0.0.1    basic_auth {
        admin $2y$14$UNITTESTbcrypthashvalue000000000000000000000000000000
    }
}
EOF
    echo "FAIL: Caddy accepted the bind/basic_auth directive collision" >&2
    exit 1
fi
echo "  ✓ parser rejects a bind/basic_auth directive collision"

# Instrument the CLI used by the existing render tests. This keeps their scenario matrix as the
# single fixture: every successful generate_caddyfile call must also adapt to non-empty JSON.
STACK_WITH_ADAPT="$TMP/pithead-with-caddy-adapt"
cp "$ROOT/pithead" "$STACK_WITH_ADAPT"
cat >>"$STACK_WITH_ADAPT" <<'EOF'

eval "$(declare -f generate_caddyfile | sed '1s/generate_caddyfile/_generate_caddyfile_unchecked/')"
generate_caddyfile() {
    local target="${1:-Caddyfile}" adapted
    _generate_caddyfile_unchecked "$@" || return
    adapted=$("$CADDY_TEST_DOCKER" run --rm -i "$CADDY_TEST_IMAGE" \
        caddy adapt --config - --adapter caddyfile <"$target") || return
    [ -n "$adapted" ] || { echo "Caddy adapted $target to empty output" >&2; return 1; }
    printf '%s\n' "$target" >>"$CADDY_TEST_ADAPT_LOG"
}
EOF
chmod +x "$STACK_WITH_ADAPT"

export CADDY_TEST_DOCKER
CADDY_TEST_DOCKER="$(command -v docker)"
export CADDY_TEST_IMAGE="$CADDY_IMAGE" CADDY_TEST_ADAPT_LOG="$TMP/adapted.log"

# shellcheck source=tests/stack/lib.sh
source "$ROOT/tests/stack/lib.sh"
trap 'rm -rf "$SANDBOX" "$TMP"' EXIT
export STACK="$STACK_WITH_ADAPT"
# The reused suites assert expected non-zero render paths; match tests/stack/run.sh's shell mode.
set +e
# shellcheck source=tests/stack/dashboard/test-dashboard.sh
source "$ROOT/tests/stack/dashboard/test-dashboard.sh"
# shellcheck source=tests/stack/dashboard/test-dashboard-onion.sh
source "$ROOT/tests/stack/dashboard/test-dashboard-onion.sh"
# shellcheck source=tests/stack/appliance/test-appliance-caddyfile-optional-env.sh
source "$ROOT/tests/stack/appliance/test-appliance-caddyfile-optional-env.sh"

[ "$FAIL" -eq 0 ] || {
    echo "FAIL: $FAIL existing Caddyfile render assertion(s) failed" >&2
    exit 1
}
adapted_count="$(wc -l <"$CADDY_TEST_ADAPT_LOG")"
[ "$adapted_count" -ge 10 ] || {
    echo "FAIL: only $adapted_count generated Caddyfiles reached Caddy" >&2
    exit 1
}
echo "  ✓ Caddy adapted all $adapted_count Caddyfiles generated by the existing render scenarios"
