#!/usr/bin/env bash
# Parse every existing render scenario with the exact Caddy image shipped by Compose.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"

if ! docker info >/dev/null 2>&1; then
    if [ -n "${CI:-}${GITHUB_ACTIONS:-}" ]; then
        echo "FAIL: Docker daemon is required for the Caddyfile parser gate in CI" >&2
        exit 1
    fi
    echo "SKIP: Docker daemon not available"
    exit 0
fi

CADDY_IMAGE="$(awk '
    $0 == "  caddy:" { service = 1; next }
    service && /^  [[:alnum:]_-]+:$/ { exit }
    service && $1 == "image:" { print $2; exit }
' "$ROOT/docker-compose.yml")"
[[ "$CADDY_IMAGE" =~ @sha256:[a-f0-9]{64}$ ]] || {
    echo "FAIL: services.caddy.image is not pinned by sha256 in docker-compose.yml" >&2
    exit 1
}
case "$CADDY_IMAGE" in */*) ;; *) CADDY_IMAGE="docker.io/library/$CADDY_IMAGE" ;; esac

# shellcheck source=tests/stack/lib.sh
source "$ROOT/tests/stack/lib.sh"
mk_tmpdir TMP
trap 'rm -rf "$SANDBOX" "$TMP"' EXIT

adapt() { docker run --rm -i "$CADDY_IMAGE" caddy adapt --config - --adapter caddyfile; }

echo "== generated Caddyfiles parse with the shipped Caddy =="

# Prove the parser rejects the directive collision that opened #1037; otherwise the green matrix
# below would establish only that the container command returned zero.
if adapt >"$TMP/invalid.json" 2>/dev/null <<'EOF'; then
https://example.invalid {
    bind 127.0.0.1    basic_auth {
        admin $2y$14$UNITTESTbcrypthashvalue000000000000000000000000000000
    }
}
EOF
    echo "FAIL: Caddy accepted the bind/basic_auth directive collision" >&2
    exit 1
fi
echo "  ✓ parser rejects a bind/basic_auth directive collision"

# Instrument the CLI used by the existing render tests. This keeps their scenario matrix as the
# single fixture: every successful generate_caddyfile call must also adapt to non-empty JSON.
STACK_WITH_ADAPT="$TMP/pithead-with-caddy-adapt"
cp "$ROOT/pithead" "$STACK_WITH_ADAPT"
cat >>"$STACK_WITH_ADAPT" <<'EOF'

eval "$(declare -f generate_caddyfile | sed '1s/generate_caddyfile/_generate_caddyfile_unchecked/')"
generate_caddyfile() {
    local target="${1:-Caddyfile}" adapted
    _generate_caddyfile_unchecked "$@" || return
    printf '%s\n' "$target" >>"$CADDY_TEST_ATTEMPT_LOG"
    adapted=$("$CADDY_TEST_DOCKER" run --rm -i "$CADDY_TEST_IMAGE" \
        caddy adapt --config - --adapter caddyfile <"$target") || {
        printf '%s\n' "$target" >>"$CADDY_TEST_FAILURE_LOG"
        return 1
    }
    [ -n "$adapted" ] || { echo "Caddy adapted $target to empty output" >&2; return 1; }
    printf '%s\n' "$target" >>"$CADDY_TEST_ADAPT_LOG"
}
EOF
chmod +x "$STACK_WITH_ADAPT"

export CADDY_TEST_DOCKER
CADDY_TEST_DOCKER="$(command -v docker)"
export CADDY_TEST_IMAGE="$CADDY_IMAGE" CADDY_TEST_ATTEMPT_LOG="$TMP/attempted.log"
export CADDY_TEST_ADAPT_LOG="$TMP/adapted.log" CADDY_TEST_FAILURE_LOG="$TMP/failed.log"
: >"$CADDY_TEST_FAILURE_LOG"

export STACK="$STACK_WITH_ADAPT"
# The reused suites assert expected non-zero render paths; match tests/stack/run.sh's shell mode.
set +e
run_suite() (
    local source_rc
    # shellcheck disable=SC2034  # read by sourced assertions and domain_ran
    PASS=0
    FAIL=0
    # shellcheck source=/dev/null
    source "$1"
    source_rc=$?
    domain_ran "$1" 0 "$source_rc"
    [ "$source_rc" -eq 0 ] && [ "$FAIL" -eq 0 ]
)

suite_failures=0
run_suite "$ROOT/tests/stack/dashboard/test-dashboard.sh" || ((suite_failures += 1))
run_suite "$ROOT/tests/stack/dashboard/test-dashboard-onion.sh" || ((suite_failures += 1))
run_suite "$ROOT/tests/stack/appliance/test-appliance-caddyfile-optional-env.sh" || ((suite_failures += 1))
run_suite "$ROOT/tests/stack/appliance/test-appliance-identity.sh" || ((suite_failures += 1))

[ "$suite_failures" -eq 0 ] || {
    echo "FAIL: $suite_failures existing Caddyfile render suite(s) failed" >&2
    exit 1
}
attempted_count="$(wc -l <"$CADDY_TEST_ATTEMPT_LOG")"
adapted_count="$(wc -l <"$CADDY_TEST_ADAPT_LOG")"
failed_count="$(wc -l <"$CADDY_TEST_FAILURE_LOG" 2>/dev/null || printf 0)"
[ "$attempted_count" -gt 0 ] && [ "$attempted_count" -eq "$adapted_count" ] && [ "$failed_count" -eq 0 ] || {
    echo "FAIL: Caddy adapted $adapted_count of $attempted_count generated files ($failed_count rejected)" >&2
    exit 1
}
echo "  ✓ Caddy adapted all $adapted_count Caddyfiles generated by the existing render scenarios"
