import json
import logging
import os
import re

from mining_dashboard.config.worker_endpoints import load_energy_config, load_worker_endpoints

logger = logging.getLogger("Config")

# --- System Configuration & Paths ---
# Base directory for shared statistics generated by the P2Pool sidecar
BASE_STATS_DIR = "/app/stats"

# Persistent storage path for application state database
DISK_PATH = "/data"
DB_FILE_PATH = os.path.join(DISK_PATH, "mining_data.db")

# Low-disk warning thresholds (% used of the data filesystem), surfaced as a top-bar badge (#138):
# a heads-up at WARN, a prominent critical alert near full. The chains keep growing and a full data
# disk corrupts monerod's DB mid-write, so this is a runtime guard distinct from the setup-time
# pre-flight estimate. (The disk *bar* uses its own colour thresholds; these gate the badge.)
DISK_WARN_PERCENT = 85
DISK_CRITICAL_PERCENT = 95

# Minimum host RAM (GB) below which the dashboard flags a low-RAM badge/alert (#104). Mirrors the
# setup/doctor pre-flight threshold; a code-level default (not a config.json knob).
# The capacity floor is MODE-AWARE: what this machine runs locally decides how much RAM it
# honestly needs (operator observation, 2026-07-31 — the old flat floor predates remote
# Monero/Tari modes). Local Tari is the famous OOM appetite; local monerod syncs heavy too; a
# coordinator with both remote is a light box. The full-local floor is 14, not 16: a nominal
# "16 GB" machine reports ~15.x usable (reserved memory, GiB-vs-GB), and the documented
# minimum spec must never wear a permanent warning. Setting LOW_RAM_GB pins a flat floor.
_LOW_RAM_ENV = os.environ.get("LOW_RAM_GB")
LOW_RAM_BASE_GB = 3  # p2pool + proxy + tor + caddy + dashboard
LOW_RAM_LOCAL_MONERO_GB = 5
LOW_RAM_LOCAL_TARI_GB = 6
# The built-in miner's own footprint, counted only when local_miner.enabled: its RandomX
# dataset is 3 GB outright as 3×1 GB pages (the unfragmented-pool case), or ~2.4 GB as 2 MB
# pages plus per-thread scratchpads and process overhead — bench-measured via smaps while both
# sides mined. 3 GB covers the reservation either way. Deliberately NOT the 6 GB headroom the
# miner's rendered config declares (hugepages_reserve_extra_mb): that is the stack's OWN
# hugepage budget, which the container floors above already count — adding it here would count
# p2pool's dataset twice.
LOW_RAM_LOCAL_MINER_GB = 3


def local_miner_enabled(path=None) -> bool:
    """Whether this box runs the built-in RigForge miner (config.json: local_miner.enabled),
    read live off the same read-only masked-config mount as the worker descriptors below — no
    env plumb, and a dashboard toggle moves the floor without a container restart. A missing or
    unreadable file reads False (DIY stacks without the mount never run the built-in miner)."""
    try:
        with open(path or HOST_CONFIG_PATH) as f:
            return json.load(f).get("local_miner", {}).get("enabled") is True
    except (OSError, ValueError, AttributeError):
        return False


def low_ram_floor_gb(monero_local: bool, tari_local: bool) -> float:
    """The least usable RAM this machine's actual workload wants, in GB."""
    if _LOW_RAM_ENV is not None:
        return float(_LOW_RAM_ENV)
    return (
        LOW_RAM_BASE_GB
        + (LOW_RAM_LOCAL_MONERO_GB if monero_local else 0)
        + (LOW_RAM_LOCAL_TARI_GB if tari_local else 0)
        + (LOW_RAM_LOCAL_MINER_GB if local_miner_enabled() else 0)
    )


def tari_is_local() -> bool:
    """The tari gRPC target sits inside the stack's own subnet — same split the Monero side
    draws with LOCAL_MONERO_HOST, derived because no LOCAL_TARI_HOST env exists."""
    prefix = ".".join(LOCAL_MONERO_HOST.split(".")[:3]) + "."
    return TARI_GRPC_ADDRESS.split(":")[0].startswith(prefix)


def monero_is_local() -> bool:
    return MONERO_NODE_HOST == LOCAL_MONERO_HOST


# Real memory PRESSURE, from live usage: warn when MemAvailable stays under this. Capacity says
# what the box could do; this says what is actually happening (operator ask, 2026-07-31).
LOW_RAM_AVAILABLE_GB = float(os.environ.get("LOW_RAM_AVAILABLE_GB", 1.5))

# --- Data Source File Paths ---
# File paths for JSON metrics generated by local collectors
STRATUM_STATS_PATH = f"{BASE_STATS_DIR}/local/stratum"
TARI_STATS_PATH = f"{BASE_STATS_DIR}/local/merge_mining"
P2P_STATS_PATH = f"{BASE_STATS_DIR}/local/p2p"
POOL_STATS_PATH = f"{BASE_STATS_DIR}/pool/stats"
NETWORK_STATS_PATH = f"{BASE_STATS_DIR}/network/stats"

# --- Network & API Configuration ---
# Host IP address used for dashboard display and worker connectivity
HOST_IP = os.environ.get("HOST_IP", "Unknown Host")

# XMRig Worker API Configuration
#
# The dashboard enriches each proxy-reported worker by probing that miner's own xmrig HTTP API
# (/1/summary) for uptime + per-miner hashrate. There is exactly ONE way it does this, derived from
# config — no auto-detection fallback. A failed probe is surfaced (api_ok=false + a logged warning),
# never silently swallowed.
#
#   XMRIG_API_AUTH  how to authenticate to the worker API:
#                     none  (default) — open, read-only API (xmrig http.restricted, no access-token).
#                                       This is the stock RigForge worker.
#                     name           — Bearer = the worker's stratum name (xmrig access-token = name).
#                     token          — Bearer = a single shared XMRIG_API_TOKEN for every worker.
#   XMRIG_API_TOKEN the shared bearer used when XMRIG_API_AUTH=token.
#   XMRIG_API_PORT  the port the worker API listens on.
#
# Upgrade note: stacks whose miners still set an xmrig access-token (the pre-open default) should set
# XMRIG_API_AUTH=name — otherwise the no-auth default probe 401s and those workers read api_ok=false.
XMRIG_API_PORT = int(os.environ.get("XMRIG_API_PORT", 8080))
XMRIG_API_AUTH = os.environ.get("XMRIG_API_AUTH", "none").strip().lower()
XMRIG_API_TOKEN = os.environ.get("XMRIG_API_TOKEN", "")
API_TIMEOUT = 1  # Connection timeout (seconds) for worker API calls

# The operator-facing stratum port xmrig-proxy publishes on the host (config.json:
# p2pool.stratum_port, #172). Display-only here — the "point your rigs at" hint and the egress
# topology label; the actual bind/publish is compose's job. p2pool's container-internal stratum
# stays fixed at :3333 regardless.
STRATUM_PORT = int(os.environ.get("STRATUM_PORT", 3333))

# The stack's internal docker bridge subnet. The dashboard runs network_mode: host and a connecting
# miner fully controls its worker name/ip via stratum, yet per-worker stats are fetched at a host
# derived from that input. A worker "ip" inside this range is the stack's OWN infrastructure (the
# Tor, monerod, p2pool) — never a real miner — so probing it would be the
# SSRF primitive in #122. Worker probes are therefore restricted to real external miner addresses;
# this range (plus loopback, link-local, etc.) is rejected. The Docker-socket proxies are no longer
# on this bridge (#345) — they sit on an isolated network published only to the host loopback, which
# this guard also rejects. Override only if you changed the subnet.
MINING_NET_CIDR = os.environ.get("MINING_NET_CIDR", "172.28.0.0/16")
try:
    # main data-loop period (s); lowered in integration tests. Tolerate a malformed override
    # rather than crashing the dashboard at import.
    UPDATE_INTERVAL = int(float(os.environ.get("UPDATE_INTERVAL", "30")))
except (TypeError, ValueError):
    UPDATE_INTERVAL = 30

# --- XvB Algorithm Constants ---
# Duration of the donation switching cycle (10 minutes)
XVB_TIME_ALGO_MS = 600000

# Minimum dwell time on a pool to ensure valid share submission (15 seconds)
XVB_MIN_TIME_SEND_MS = 15000

# Wallet address used for fetching XvB bonus history and pool identification
MONERO_WALLET_ADDRESS = os.environ.get("MONERO_WALLET_ADDRESS", "")

# On-chain payout confirmation (#381). When enabled, the dashboard polls a view-only
# monero-wallet-rpc (scanning the local node) for confirmed incoming payouts, persists them, and
# fires a payout_confirmed alert. pithead renders PAYOUT_CONFIRM_ENABLED=true only when a view key
# is set on a local node, so an unset view key (the default) means the wallet-rpc container isn't
# started and this poll never runs. The wallet-rpc login is a capability cred (owner-only .env); the
# URL is the host-loopback publish reachable via the dashboard's host networking.
PAYOUT_CONFIRM_ENABLED = os.environ.get("PAYOUT_CONFIRM_ENABLED", "false").strip().lower() == "true"
MONERO_WALLET_RPC_URL = os.environ.get("MONERO_WALLET_RPC_URL", "http://127.0.0.1:18082/json_rpc")
WALLET_RPC_USERNAME = os.environ.get("WALLET_RPC_USERNAME", "wallet")
WALLET_RPC_PASSWORD = os.environ.get("WALLET_RPC_PASSWORD", "")

# Unique Donor ID for the XMRvsBeast pool
XVB_DONOR_ID = os.environ.get("XVB_DONOR_ID", "")

# Feature Flag: Toggles the XvB algorithmic switching logic
ENABLE_XVB = os.environ.get("XVB_ENABLED", "true").lower() == "true"

# The bridge container's Tor SOCKS proxy, shared by every dashboard call that must reach clearnet
# without leaking the host IP: the XvB stats fetch + raffle registration (#163), the update check
# (#224), and the Healthchecks.io ping (#79). socks5h resolves the target host via Tor too (no local
# DNS leak). The host-networked dashboard reaches it at 172.28.0.25:9050 (tracks the subnet, #180).
TOR_SOCKS_PROXY = os.environ.get("TOR_SOCKS_PROXY", "socks5h://172.28.0.25:9050")

# Route XvB DONATION MINING through Tor by default too (#166), not just the stats fetch (#163): while
# donating, the proxy connects to na.xmrvsbeast.com, which would otherwise expose the host IP. The
# algo controller sets this host:port as the XvB pool's per-pool `socks5` field (xmrig-proxy resolves
# that pool's DNS proxy-side). `xvb.tor: false` opts out (direct, for max yield). The host:port is
# derived from TOR_SOCKS_PROXY (so a custom subnet, #180, carries through) with the scheme stripped —
# xmrig wants a bare host:port.
XVB_TOR_ENABLED = os.environ.get("XVB_TOR_ENABLED", "true").lower() == "true"
XVB_TOR_SOCKS5 = TOR_SOCKS_PROXY.split("://", 1)[-1]

# XvB raffle-registration endpoint (#263). Mining to the XvB pool isn't enough to enter the raffle —
# a wallet is only entered once it's registered against this endpoint (and only if it already has a
# share in the P2Pool PPLNS window). Same host as the XvB stats fetch above. The operator asked us
# not to *advertise* this API ("to mitigate abuse"), so don't surface the bare URL in user-facing
# docs/README — but it ships here as the working default. Override with XVB_SUBMIT_URL (e.g. a test
# server); set it to a disable sentinel (off/none/false/disabled/0) to turn auto-registration off
# while keeping XvB on. The call ALWAYS rides Tor (TOR_SOCKS_PROXY) like the stats fetch (#163) since it
# carries the full wallet — it is NOT subject to the xvb.tor donation opt-out.
#
# Contract — GET ?address=<full wallet>, verified live 2026-06-28:
#   2xx                                              => freshly registered
#   422 "ERROR: Wallet Address Already Registered"   => already in (idempotent success)
#   422 "ERROR: Invalid Wallet Address"              => bad wallet (permanent — stop retrying)
#   no-share / 5xx / other                           => transient, retry on the next poll
_XVB_SUBMIT_DEFAULT = "https://xmrvsbeast.com/cgi-bin/p2pool_bonus_submit_api.cgi"
_XVB_SUBMIT_DISABLE_SENTINELS = {"off", "none", "false", "disabled", "0"}
_xvb_submit_env = os.environ.get("XVB_SUBMIT_URL", "").strip()
if _xvb_submit_env.lower() in _XVB_SUBMIT_DISABLE_SENTINELS:
    XVB_SUBMIT_URL = ""  # auto-registration explicitly disabled (XvB itself still runs)
else:
    XVB_SUBMIT_URL = _xvb_submit_env or _XVB_SUBMIT_DEFAULT

# How often to re-register with XvB once eligible (#263), seconds. Registration is idempotent, so we
# re-run on a daily cadence: it picks up the operator's newer security-token behaviour and re-enters
# a long-offline miner cleanly.
XVB_REGISTER_INTERVAL_S = 24 * 3600

# --- Egress posture knobs (#170 Component Health panel) ---
# Surfaced so the dashboard can show each component's outbound egress route + a privacy roll-up.
# Defaults are the privacy-safe resting state (firewall fail-closed; p2pool peers over Tor); pithead
# renders the real values into the dashboard env (docker-compose.yml) so the panel reflects actual
# config rather than a hardcoded guess. TOR_EGRESS_FIREWALL is the #270 network-layer backstop: when
# on, any non-Tor egress from the container subnet is DROPPED (fail-closed), so the whole stack is
# Tor-only regardless of per-app config.
TOR_EGRESS_FIREWALL = os.environ.get("TOR_EGRESS_FIREWALL", "true").strip().lower() == "true"
P2POOL_CLEARNET = os.environ.get("P2POOL_CLEARNET", "false").strip().lower() == "true"

# New-release check (#224, config.json: dashboard.check_for_updates). Default ON — the dashboard asks
# GitHub for the latest release and shows a header badge linking to it if it's newer than the running
# version. Notify-only (no upgrade — that's #59). The check is routed over the same bridge Tor SOCKS
# as XvB (socks5h, so DNS goes through Tor too), so it reveals neither the host IP nor a DNS lookup to
# GitHub — which is why it's safe to default on; it fails silently offline. Opt out with `false`.
CHECK_FOR_UPDATES = os.environ.get("DASHBOARD_CHECK_UPDATES", "true").strip().lower() == "true"

# --- Dashboard control channel (#33, config.json: dashboard.control.enabled) ---
# Default OFF. When on, the config-editing routes (/api/config, /api/control/*) are registered and
# the dashboard may write typed JSON intents into the requests/ spool, which a host-side runner
# (pithead control-run-pending) validates and applies. The container's only write access is
# CONTROL_REQUESTS_DIR; results/ and audit/ are mounted read-only and staged intents never enter
# the container at all — that rw/ro split is the trust boundary (see docker-compose.yml).
DASHBOARD_CONTROL_ENABLED = (
    os.environ.get("DASHBOARD_CONTROL_ENABLED", "false").strip().lower() == "true"
)
CONTROL_REQUESTS_DIR = os.environ.get("CONTROL_REQUESTS_DIR", "/control/requests")
CONTROL_RESULTS_DIR = os.environ.get("CONTROL_RESULTS_DIR", "/control/results")
# Host-written security logs, surfaced read-only (#349). control.log is the #33 audit trail
# (one JSON line per handled control request); access.log is Caddy's JSON access log — both are
# written and rotated host-side, and every field read from them is sanitized before serving.
CONTROL_AUDIT_LOG = os.environ.get("CONTROL_AUDIT_LOG", "/control/audit/control.log")
ACCESS_LOG_PATH = os.environ.get("ACCESS_LOG_PATH", "/access-log/access.log")
# The PRE-MASKED config copy, bind-mounted read-only for form prefill (#440): the host renders it
# with every set secret leaf already replaced by the sentinel, so the container never holds a raw
# secret. The raw config.json is not mounted into the container at all.
HOST_CONFIG_PATH = os.environ.get("HOST_CONFIG_PATH", "/control/masked/config.json")
# config.reference.json (every key with its default), bind-mounted read-only. read_config merges it
# UNDER the operator's sparse config.json so the editor form covers the full schema, not just the
# keys the operator happens to have set (#33 "edit every setting"). A missing reference degrades to
# the host config alone.
HOST_REFERENCE_PATH = os.environ.get("HOST_REFERENCE_PATH", "/host-config/config.reference.json")
# config.core-keys.json (#502/#529): the wizard's core-key shortlist, bind-mounted read-only. The
# SAME file the wizard reads, so the Configuration view can pin the SAME shortlist at the top of
# the form instead of hand-maintaining a duplicate list. A missing/unreadable file degrades to no
# core group (control_service.read_config falls back to an empty list).
HOST_CORE_KEYS_PATH = os.environ.get("HOST_CORE_KEYS_PATH", "/host-config/config.core-keys.json")
OS_UPDATE_STATE_PATH = os.environ.get(
    "OS_UPDATE_STATE_PATH", "/control/results/os-update-state.json"
)

WORKER_READ_TOKENS_PATH, DASHBOARD_WORKERS = "/control/masked/worker-read-tokens.json", None


def current_worker_endpoints():
    return (
        DASHBOARD_WORKERS
        if DASHBOARD_WORKERS is not None
        else load_worker_endpoints(HOST_CONFIG_PATH, WORKER_READ_TOKENS_PATH)
    )


DASHBOARD_ENERGY = load_energy_config(HOST_CONFIG_PATH)
CONTROL_WAIT_S = float(os.environ.get("CONTROL_WAIT_S", 30))
CONTROL_WORKER_UPGRADE_WAIT_S = float(os.environ.get("CONTROL_WORKER_UPGRADE_WAIT_S", 300))
GITHUB_RELEASES_API = os.environ.get(
    "GITHUB_RELEASES_API",
    "https://api.github.com/repos/p2pool-starter-stack/pithead/releases/latest",
)
# Latest RigForge release, for the per-worker "new version available" badge (#596). Same check,
# same Tor route, same dashboard.check_for_updates gate as the stack's own release check above.
GITHUB_RIGFORGE_RELEASES_API = os.environ.get(
    "GITHUB_RIGFORGE_RELEASES_API",
    "https://api.github.com/repos/p2pool-starter-stack/rigforge/releases/latest",
)
UPDATE_CHECK_INTERVAL = int(float(os.environ.get("UPDATE_CHECK_INTERVAL", "3600")))

# Donation tier to target (config.json: xvb.donation_level). The XvB raffle picks
# winners at random, so donating above a tier's threshold buys nothing — we aim to
# just clear it and send the rest to p2pool.
#   "auto" (default)  — highest tier the current hashrate can sustain
#   "donor"/"vip"/"whale"/"mega" — a specific named tier, honored even if the
#       hashrate can't sustain it (the dashboard shows a warning badge then)
XVB_DONATION_LEVEL = os.environ.get("XVB_DONATION_LEVEL", "auto").strip().lower()

# --- Upstream Pool Configuration ---
P2POOL_URL = os.environ.get("P2POOL_URL", "")
XVB_POOL_URL = os.environ.get("XVB_POOL_URL", "")

# --- Proxy API Configuration ---
PROXY_AUTH_TOKEN = os.environ.get("PROXY_AUTH_TOKEN", "")
PROXY_HOST = os.environ.get("PROXY_HOST", "127.0.0.1")
PROXY_API_PORT = int(os.environ.get("PROXY_API_PORT", 3344))

# --- Docker Proxy Configuration ---
# Both socket proxies are isolated on their own network and published only to the host loopback
# (#345), so the host-networked dashboard reaches them here while no mining container can. Compose
# sets these explicitly; the loopback defaults keep a bare run working.
# Read-only socket proxy: container stats/logs only (no write access).
DOCKER_PROXY_URL = os.environ.get("DOCKER_PROXY_URL", "tcp://127.0.0.1:12375")
# Control socket proxy: start/stop only, used to reject/readmit workers on node-down
# (Issue #31). A separate proxy so opening POST for start/stop can't widen the read-only
# proxy's access. See docker-compose.yml `docker-control`.
DOCKER_CONTROL_URL = os.environ.get("DOCKER_CONTROL_URL", "tcp://127.0.0.1:12376")
LOG_TAIL_LINES = int(os.environ.get("LOG_TAIL_LINES", 100))
DOCKER_TIMEOUT = int(os.environ.get("DOCKER_TIMEOUT", 5))

# --- Monero is required; Tari is optional (Issues #31, #35, #51) ---
# monerod is the chain the stack actually mines: if it's unreachable or still syncing, the
# workers can't mine no matter what, so those behaviours aren't configurable.
#   - A monerod outage ALWAYS rejects workers (stops xmrig-proxy → closes :3333) so miners
#     fail over to the backup pools they've configured instead of idling on us (Issue #31).
#   - The miner (p2pool + xmrig-proxy) is ALWAYS held until monerod has fully synced — it
#     can't mine against an unsynced node, and p2pool's merge-mining chatter would just flood
#     the logs during the hours-long initial sync (Issue #35).
#
# Tari is merge-mining gravy — you can mine Monero on p2pool without it — so a Tari outage
# NEVER rejects workers, regardless of `dashboard.tari_required`; p2pool keeps mining Monero
# through it and the outage surfaces in the Tari panel/alerts instead (Issue #897). What
# `tari_required` (default true) still decides is how much Tari blocks the *rest* of the
# stack: true makes the miner wait for Tari's initial sync too, and drives the full Sync-Mode
# dashboard for a Tari-only (re)sync. Set it false to make Tari NON-BLOCKING there as well:
# start the miner as soon as monerod is synced (Tari finishes in the background), and keep
# the operational dashboard — with a "Tari syncing" indicator — instead of the takeover
# screen (Issue #51).
TARI_REQUIRED = os.environ.get("TARI_REQUIRED", "true").strip().lower() == "true"

# Container the dashboard stops/starts to reject/readmit workers on a monerod outage.
REJECT_WORKERS_CONTAINER = os.environ.get("REJECT_WORKERS_CONTAINER", "xmrig-proxy")

# Containers held stopped until the required chain(s) finish syncing, then started together
# (p2pool first so the proxy has something to connect to). Comma-separated; order preserved.
# The hold is a one-way latch: after the first release we never re-hold (a later node blip is
# #31's job — it stops only xmrig-proxy so p2pool keeps its sidechain position), and the latch
# is persisted across dashboard restarts so a restart mid-sync doesn't prematurely release.
SYNC_GATE_CONTAINERS = [
    c.strip()
    for c in os.environ.get("SYNC_GATE_CONTAINERS", "p2pool,xmrig-proxy").split(",")
    if c.strip()
]

# Opt-in fail-closed miner hold on an UNRECOVERABLE health failure (#490), `dashboard.fail_closed`,
# default false. The dashboard is an observability layer, not the mining datapath (xmrig-proxy ->
# p2pool -> monerod is independent of it), so the default posture is alert-only: a cosmetic
# dashboard fault must never idle the fleet. `true` reuses the #35 sync-gate's own mechanism
# (stop/start SYNC_GATE_CONTAINERS) to hold the miner until the failure clears — see
# DataService._apply_fail_closed_gate for what counts as "unrecoverable" (narrowly: DB recovery
# itself failing, or the dashboard container crash-looping — never a transient blip).
DASHBOARD_FAIL_CLOSED = os.environ.get("DASHBOARD_FAIL_CLOSED", "false").strip().lower() == "true"

# Debounce: a node must be unreachable this long before it's declared DOWN, and reachable
# this long before recovery — so a single transient timeout or a brief restart doesn't
# kick every miner to their backups (and back) on a blip.
NODE_DOWN_AFTER_SEC = int(os.environ.get("NODE_DOWN_AFTER_SEC", 90))
NODE_RECOVERY_AFTER_SEC = int(os.environ.get("NODE_RECOVERY_AFTER_SEC", 60))

# Peer-loss staleness (#972): a reachable monerod reporting `synchronized: false` must persist
# this long before the out-of-sync alert fires. 10 minutes rides out normal tip-lag blips AND
# the coupled monerod restart after a tor recreate (compose depends_on restart / tor_heal), so
# only a node that genuinely failed to re-peer alarms. Env-only (tests/mini-stack), not a
# config.json knob — nobody should have to tune a detector.
NODE_STALE_AFTER_SEC = int(os.environ.get("NODE_STALE_AFTER_SEC", 600))

# --- Healthchecks.io dead-man's switch (Issue #79) ---
# Optional external liveness monitor. Set a ping URL and the dashboard loop pings it every cycle;
# if the whole host dies (power loss, kernel panic, NIC death) the dashboard dies with it, the pings
# stop, and Healthchecks.io alerts the operator on the *absence* of a ping — the one failure mode an
# in-stack notifier (#45) structurally can't report. Off until configured: a blank ping URL is the
# off switch (nothing pings, no errors). The ping always rides Tor (TOR_SOCKS_PROXY), so it's never
# a clearnet beacon — paste a Tor-reachable URL (hosted hc-ping.com, or a self-hosted onion/public
# instance; a LAN-only self-hosted address is unreachable through Tor).
HEALTHCHECKS_PING_URL = os.environ.get("HEALTHCHECKS_PING_URL", "").strip()

# --- Tor guard self-heal (#424) ---
# Opt-in (tor.auto_heal in config.json): when true, the dashboard probes Tor clearnet egress (the
# same generate_204-through-SOCKS probe as the doctor check) and restarts the tor container when
# exits stay stuck on a failing guard — bounded retries, long cooldown, loud logging (see
# service/health/tor_heal.py). Off by default: a tor restart drops every circuit, mining onions included,
# so the stack must not restart its privacy boundary unbidden.
TOR_AUTO_HEAL = os.environ.get("TOR_AUTO_HEAL", "false").strip().lower() == "true"

# --- Operator alerts: Telegram (Issue #121) ---
# Notifications-only Telegram pusher: a thin notifier that pushes a small, high-value set of
# operational edges (node down/recovered, worker offline/back, sync finished) to one chat.
# Disabled by default — with TELEGRAM_ENABLED unset/false the stack runs with no Telegram
# config and never sends or errors. The interactive bot / command interface is a separate
# feature (#45); this is the notifications-only split.
#
# `bot_token` is a secret: the pithead CLI renders it into the owner-only .env (like the node
# RPC password), and the notifier never writes it to a log line. On a Tor-only / no-clearnet
# host the Telegram API is unreachable and sends fail silently (consistent with #59).
TELEGRAM_ENABLED = os.environ.get("TELEGRAM_ENABLED", "false").strip().lower() == "true"
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "").strip()

# Interactive command interface (#45), separate opt-in from the alerts above. When on, the
# dashboard long-polls Telegram (getUpdates — outbound only, no inbound port) and answers
# read-only status commands from the configured chat_id. Off by default; the alerter works
# without it. See telegram_commands.py / docs/telegram.md.
TELEGRAM_COMMANDS_ENABLED = (
    os.environ.get("TELEGRAM_COMMANDS_ENABLED", "false").strip().lower() == "true"
)

# Two-way control commands (#338): /restart and /apply, handled by the same bot. OFF by default and
# independent of the read-only commands above. It rides the #33 host-control spool (so it also needs
# DASHBOARD_CONTROL_ENABLED) and acts only for the allow-listed Telegram USER ids, each action gated
# by an explicit in-chat confirmation that fails closed on timeout. Empty allow-list ⇒ inert (no id
# can ever confirm). The bot token being known is NOT authorization. See telegram_commands.py.
TELEGRAM_CONTROL_ENABLED = (
    os.environ.get("TELEGRAM_CONTROL_ENABLED", "false").strip().lower() == "true"
)
# Allow-list of Telegram numeric user ids, rendered by pithead as a comma list; split on commas or
# whitespace and kept as strings for exact equality against the id Telegram sends.
TELEGRAM_CONTROL_ALLOWED_IDS = frozenset(
    tok
    for tok in re.split(r"[,\s]+", os.environ.get("TELEGRAM_CONTROL_ALLOWED_IDS", "").strip())
    if tok
)
# Deny-on-timeout window (seconds): an issued control command must be confirmed within this, else it
# is denied — never queued.
TELEGRAM_CONTROL_CONFIRM_S = float(os.environ.get("TELEGRAM_CONTROL_CONFIRM_S", 60))


def _telegram_event_enabled(name, default=True):
    """Read one per-event toggle from TELEGRAM_EVENT_<NAME> (rendered from config.json's
    telegram.events by pithead). Any toggle left unset defaults to on, so enabling Telegram
    turns on the full set and an operator only has to opt *out* of the noisy ones."""
    raw = os.environ.get(f"TELEGRAM_EVENT_{name.upper()}")
    if raw is None or raw.strip() == "":
        return default
    return raw.strip().lower() == "true"


# Per-event delivery toggles. Keys here are the canonical event names used throughout the
# alerter (AlertService.EVT_*) and must match the config.json telegram.events block.
TELEGRAM_EVENTS = {
    "node_down": _telegram_event_enabled("node_down"),
    "node_recovered": _telegram_event_enabled("node_recovered"),
    "worker_offline": _telegram_event_enabled("worker_offline"),
    "worker_recovered": _telegram_event_enabled("worker_recovered"),
    "worker_joined": _telegram_event_enabled("worker_joined"),
    "worker_left": _telegram_event_enabled("worker_left"),
    "sync_finished": _telegram_event_enabled("sync_finished"),
    "disk_space": _telegram_event_enabled("disk_space"),
    "db_unhealthy": _telegram_event_enabled("db_unhealthy"),
    "db_reset": _telegram_event_enabled("db_reset"),
    "xvb_no_share": _telegram_event_enabled("xvb_no_share"),
    "clearnet_exposed": _telegram_event_enabled("clearnet_exposed"),
    "xvb_registration": _telegram_event_enabled("xvb_registration"),
    "new_release": _telegram_event_enabled("new_release"),
    "stack_online": _telegram_event_enabled("stack_online"),
    "daily_summary": _telegram_event_enabled("daily_summary"),
    "hashrate_low": _telegram_event_enabled("hashrate_low"),
    "hashrate_loss": _telegram_event_enabled("hashrate_loss"),
    "hugepages": _telegram_event_enabled("hugepages"),
    "low_ram": _telegram_event_enabled("low_ram"),
    "wallet_changed": _telegram_event_enabled("wallet_changed"),
    "high_reject_rate": _telegram_event_enabled("high_reject_rate"),
    "block_found": _telegram_event_enabled("block_found"),
    "payout_found": _telegram_event_enabled("payout_found"),
    "payout_confirmed": _telegram_event_enabled("payout_confirmed"),
    "container_unhealthy": _telegram_event_enabled("container_unhealthy"),
    "raffle_win": _telegram_event_enabled("raffle_win"),
}
# ponytail: daily_summary is a scheduled push, not an edge — it lives in the events dict only so it
# gets a per-event on/off toggle like the rest; its time is TELEGRAM_DAILY_SUMMARY_TIME below.

# Local time (HH:MM, 24-hour) to push the once-daily status digest, when the daily_summary event is
# on. Uses the dashboard container's timezone (dashboard.timezone), so "08:00" means 8am wherever
# the box is. Rendered from config.json telegram.daily_summary_time.
TELEGRAM_DAILY_SUMMARY_TIME = os.environ.get("TELEGRAM_DAILY_SUMMARY_TIME", "08:00").strip()

# --- Operator alerts: webhook + ntfy sinks (#380) ---
# Push-only siblings of the Telegram alerter: every alert AlertService emits also POSTs to each
# configured webhook URL (as JSON) and to an ntfy topic URL (as the message body). All off by
# default — no URLs means nothing new runs. The URLs and the ntfy token are secrets (webhook
# query strings often carry tokens): rendered into the owner-only .env and never logged.
# Rendered from config.json's notifications block by pithead.
NOTIFY_WEBHOOK_URLS = os.environ.get("NOTIFY_WEBHOOK_URLS", "").split()
NTFY_URL = os.environ.get("NTFY_URL", "").strip()
NTFY_TOKEN = os.environ.get("NTFY_TOKEN", "").strip()
# Route the webhook/ntfy POSTs over Tor (default), so the endpoint sees a Tor exit, not the host
# IP — the same egress rule as Telegram (#340). notifications.tor:false opts out for LAN /
# self-hosted endpoints (Tor exits can't reach RFC1918 addresses); flipping it makes clearnet
# endpoints see the host IP.
NOTIFY_TOR = os.environ.get("NOTIFY_TOR", "true").strip().lower() == "true"

# Hashrate-degradation detector (Issue #99). Flags a sustained drop in total hashrate below
# HASHRATE_DROP_THRESHOLD_PCT of its trailing baseline for HASHRATE_DROP_MINUTES minutes — surfaced
# as a chart event marker (always on) and, when telegram.events.hashrate_loss is on, an alert.
# Rendered from config.json dashboard.hashrate_drop_threshold / dashboard.hashrate_drop_minutes.
HASHRATE_DROP_THRESHOLD_PCT = int(float(os.environ.get("HASHRATE_DROP_THRESHOLD_PCT", 50)))
HASHRATE_DROP_MINUTES = int(float(os.environ.get("HASHRATE_DROP_MINUTES", 10)))

# Worker offline/online debounce (Issue #121). A worker must be unseen this long before it's
# reported OFFLINE, and seen continuously this long before "back online" — so a brief miner
# reconnect doesn't spam the chat. Workers flap more than nodes (rig reboots, Wi-Fi blips),
# so the window is wider than the node debounce above.
WORKER_OFFLINE_AFTER_SEC = int(os.environ.get("WORKER_OFFLINE_AFTER_SEC", 300))
WORKER_RECOVERY_AFTER_SEC = int(os.environ.get("WORKER_RECOVERY_AFTER_SEC", 120))

# --- Monero Configuration ---
# Used to determine if the node is local (Docker) or remote
MONERO_NODE_HOST = os.environ.get("MONERO_NODE_HOST", "172.28.0.26")
# The local monerod's bridge IP — used to tell a local node from a remote one (that split drives
# log-scraping vs. RPC probing). Tracks the configurable subnet prefix (#180), set by the compose
# dashboard env; MONERO_NODE_HOST equals this exactly when monero.mode is local.
LOCAL_MONERO_HOST = os.environ.get("LOCAL_MONERO_HOST", "172.28.0.26")

# monerod's get_info RPC, used to read sync height/target directly instead of scraping
# docker logs (Issue #29). Reachable because the dashboard runs network_mode: host and
# monerod publishes 127.0.0.1:18081. Credentials are required by monerod's restricted-rpc
# + rpc-login (digest auth); absent creds simply make the RPC fail and fall back to logs.
MONERO_RPC_URL = os.environ.get("MONERO_RPC_URL", "http://127.0.0.1:18081")
MONERO_NODE_USERNAME = os.environ.get("MONERO_NODE_USERNAME", "")
MONERO_NODE_PASSWORD = os.environ.get("MONERO_NODE_PASSWORD", "")

# Whether the bundled monerod is configured to prune the blockchain (config.json
# monero.prune → MONERO_PRUNE). Used to label the node Pruned/Full in the UI (Issue #32);
# only meaningful for a local node (we don't control a remote node's pruning).
# pithead renders this as 1/0 (the form monerod's CLI wants), so accept the numeric/boolean
# truthy forms — not just "true", which silently read pruned nodes as Full before (the
# pruned/full label is purely display, #32).
MONERO_PRUNE = os.environ.get("MONERO_PRUNE", "true").strip().lower() in ("true", "1", "yes", "on")

# --- Optional clearnet initial sync auto-transition (#183/#234) ---
# When monero.clearnet_initial_sync / tari.clearnet_initial_sync is on, the daemon does its initial
# block download over clearnet (fast) instead of Tor. The supervisor watches the per-chain "synced"
# signal the data loop already computes and, the first time a clearnet node reports synced, drops a
# persistent marker in CLEARNET_STATE_DIR and restarts the container — whose entrypoint, seeing the
# marker, comes back up Tor-only. Default off. Truthy parsing matches MONERO_PRUNE.
MONERO_CLEARNET_SYNC = os.environ.get("MONERO_CLEARNET_SYNC", "false").strip().lower() in (
    "true",
    "1",
    "yes",
    "on",
)
TARI_CLEARNET_SYNC = os.environ.get("TARI_CLEARNET_SYNC", "false").strip().lower() in (
    "true",
    "1",
    "yes",
    "on",
)
# Shared, dashboard-writable dir holding the per-chain "<name>.synced" transition markers. Mounted
# read-only into monerod/tari at the same path. Container default matches the compose mount.
CLEARNET_STATE_DIR = os.environ.get("CLEARNET_STATE_DIR", "/clearnet-state")

# --- Tari Configuration ---
# Connection details for the Tari Base Node and Block Explorer
TARI_GRPC_ADDRESS = os.environ.get("TARI_GRPC_ADDRESS", "127.0.0.1:18142")

# Tari on-chain payout confirmation (#462), the Tari sibling of #381. When enabled, the dashboard
# streams a view-only minotari_console_wallet's completed transactions (it scans the local Tari
# node) for confirmed incoming payouts, persists them to the shared payouts table with chain="tari",
# and fires the shared payout_confirmed alert. pithead renders TARI_PAYOUT_CONFIRM_ENABLED=true only
# when a tari view key is set on a LOCAL Tari node, so an unset view key (the default) means the
# tari-wallet container isn't started and this poll never runs. The wallet gRPC is unauthenticated
# (like the Tari base node); it is reached over the host loopback publish (127.0.0.1:18143).
TARI_PAYOUT_CONFIRM_ENABLED = (
    os.environ.get("TARI_PAYOUT_CONFIRM_ENABLED", "false").strip().lower() == "true"
)
TARI_WALLET_GRPC_ADDRESS = os.environ.get("TARI_WALLET_GRPC_ADDRESS", "127.0.0.1:18143")

# --- XvB Donation Controller (Issues #9, #70) ---
# Closed-loop controller. The raffle pays nothing above a tier threshold, so the
# objective is: hold XvB's *reported* 1h average just above the tier on minimum
# donation, send everything else to p2pool, and never donate so much that p2pool
# stops finding shares (which would forfeit "VIP" status — non-VIP winners are
# skipped and failed). It steers off XvB's own hard numbers and self-calibrates,
# so it holds the tier regardless of how XvB scales our donation. Validated by the
# closed-loop simulator in mining_dashboard/sim/donation_model.py.

# Hard ceiling on the donated fraction, independent of the VIP reserve below. A
# last-resort cap so a misconfigured/zero difficulty reading can never donate the
# whole cycle.
XVB_MAX_DONATION_FRACTION = float(os.environ.get("XVB_MAX_DONATION_FRACTION", 0.85))

# Cushion held above the tier threshold: the controller targets the 1h average at
# threshold * (1 + pct), capped in ABSOLUTE H/s. The raffle terminates a win if the
# 1h average dips below the round minimum, so the cushion must exceed the credited
# average's own noise. Measured on a live whale-tier fleet (#769): XvB's credited 1h
# dipped ~2.5 kH/s below the setpoint, sailing straight through the old 1 kH/s cap
# and killing won rounds. 5% capped at 5 kH/s clears that observed noise at every
# tier while still capping the waste a flat percentage would cost the higher tiers.
XVB_MAINT_MARGIN_PCT = float(os.environ.get("XVB_MAINT_MARGIN_PCT", 0.05))
XVB_MAINT_MARGIN_ABS_CAP = float(os.environ.get("XVB_MAINT_MARGIN_ABS_CAP", 5000))

# How long after a recorded raffle win the controller treats the won round as
# possibly still live and refuses to steer the donation DOWN (#769): a round runs
# ~60 min and then until the bonus finds a share, so 90 min covers the round plus
# its tail. During this hold only downward calibration steps are skipped — upward
# steps, the VIP reserve clamp, and the stale-read fail-safes all still apply.
XVB_WIN_ROUND_HOLD_S = float(os.environ.get("XVB_WIN_ROUND_HOLD_S", 5400))

# Integral gain of the calibration loop. Each cycle the donated fraction is nudged
# by gain * (reference - measured_1h) / current_hr. Low by design: the 1h average
# is laggy, so high gain hunts (the simulator finds oscillation above ~0.05,
# especially if XvB over-credits). 0.03 converges in a few hours and stays stable.
XVB_CONTROL_GAIN = float(os.environ.get("XVB_CONTROL_GAIN", 0.03))

# Projection horizon of the loop's protective steering. The 1h average the loop
# steers off lags what we actually route by up to the whole rolling window, so at
# a margin-riding equilibrium a decaying credited average can reach the round
# minimum before the reactive loop has moved — measured live: ~19 minutes from a
# won round's draw to the terminating dip, with the ramp-back landing 4 minutes
# too late. Each advance the controller also projects the credited trend this
# many seconds forward and steers off min(measured, projected): projection only
# ever tightens steering, never slackens it, so its worst case is the reactive
# loop's behavior plus an earlier ramp. 0 disables projection. Default 20 min —
# inside the measured decay-to-threshold window, and short enough that a full
# window turnover never doubles a real trend.
XVB_PROJECTION_HORIZON_S = float(os.environ.get("XVB_PROJECTION_HORIZON_S", 1200))

# Age past which a frozen XvB stats read is treated as stale (#311). A successful
# fetch lands every ~10 poll cycles (data_service throttle) and only a real fetch
# bumps `last_update` (#136), so its age IS the fetch age. When the fetch goes quiet
# (e.g. a stuck Tor circuit) `avg_1h` freezes; steering off that frozen number
# over-donates against a target we can't refresh. Past this age the controller holds
# the last split instead of chasing it. Default ~3 fetch intervals.
XVB_STATS_STALE_AFTER_S = float(os.environ.get("XVB_STATS_STALE_AFTER_S", 3 * 10 * UPDATE_INTERVAL))

# Fail-safe for a PROLONGED stale read. Holding the last split (above) is right for a
# brief blip, but through a multi-hour outage it keeps donating blind — and if staleness
# began mid-ramp it holds a high fraction (over-donation, #70 territory). Past this longer
# grace the controller stops trusting the frozen number and DECAYS the held donation
# fraction toward 0 each advance cycle: when we can't confirm we still need to donate, stop
# wasting hashrate. A fresh fetch resumes normal control. Default 30 min (> the hold grace).
XVB_STALE_DECAY_AFTER_S = float(os.environ.get("XVB_STALE_DECAY_AFTER_S", 1800))

# VIP / PPLNS reserve. To stay "VIP" we must keep finding p2pool shares, so we
# reserve enough hashrate for p2pool to hold a share in the PPLNS window. The bare
# minimum (one expected share per window) is sidechain_difficulty / window_seconds;
# this factor multiplies it for headroom against Poisson variance (2.0 => ~2
# expected shares, P(zero) ~ 13%). Donation is capped so p2pool always keeps at
# least this. Falls back to XVB_MAX_DONATION_FRACTION when difficulty is unknown.
XVB_P2POOL_RESERVE_FACTOR = float(os.environ.get("XVB_P2POOL_RESERVE_FACTOR", 2.0))

# Switching overhead (ms) to account for connection ramp-up time
XVB_SWITCH_OVERHEAD_MS = 5000

# --- XvB warm-standby, backup stack (#249, config.json: xvb.standby.source) ---
# On a two-host failover pair (same wallet, workers list both in pools[]), the BACKUP points this at
# the PRIMARY's dashboard so it can pull the primary's XvB controller state and hold it as standby —
# so when workers fail over, the backup resumes the donation split warm instead of cold-ramping for
# hours. Blank (the default) = off: an ordinary single stack never pulls. The value is the full URL
# of the primary's read-only endpoint (e.g. https://<primary-onion>/api/xvb-standby, or a LAN
# http://host:port/api/xvb-standby); an .onion source rides the bridge Tor SOCKS, a LAN source dials
# direct — no new clearnet egress either way. It is a capability URL (it can carry the primary's
# dashboard basic-auth as userinfo), so pithead renders it into the owner-only .env and masks it in
# the control-channel config, exactly like the Healthchecks ping URL.
XVB_STANDBY_SOURCE = os.environ.get("XVB_STANDBY_SOURCE", "").strip()
# How often the backup re-pulls the primary's state (seconds). A code-level constant, not a knob:
# the state moves slowly (the closed loop steps once per 10-min cycle), so a minute is ample.
XVB_STANDBY_INTERVAL_S = 60

# --- Data Retention Policies ---
HISTORY_RETENTION_SEC = 30 * 24 * 3600  # 30 Days
# How long an offline worker lingers in the live "Workers Alive" table before it falls off (#182).
# Operates on the live proxy-sourced list. A reconnect re-adds the worker. 1h keeps a
# just-disconnected rig visible (shown as DOWN) but clears ghosts.
WORKER_FALLOFF_SEC = 3600  # 1 Hour

# --- Hashrate averaging windows (#168) ---
# xmrig-proxy's /workers rows expose five native per-worker averaging windows. The chart lets the
# operator pick which one to plot; these keys are the canonical identifiers shared by the collector,
# the storage schema, and the /api/state `avg` query param. Shorter windows show responsiveness (a
# rig dropping/joining spikes within a poll or two); longer windows show the smoothed trend.
HASHRATE_WINDOWS = ["1m", "10m", "1h", "12h", "24h"]
# Default plotted window. 10m is today's headline series, so the default chart is unchanged AND keeps
# its full history (it reuses the original v_p2pool/v_xvb columns below). The other four are captured
# and persisted going FORWARD only — pre-#168 history has no per-window data and reads 0 there, and
# the 12h/24h averages also need that much rig uptime to fill (signposted in the UI).
DEFAULT_HASHRATE_WINDOW = "10m"
# window -> (p2pool column, xvb column) in the history table. 10m maps to the original pair so the
# default view and all existing rows stay intact; the rest are additive columns (see _migrate_db).
HASHRATE_WINDOW_COLUMNS = {
    "1m": ("v_p2pool_1m", "v_xvb_1m"),
    "10m": ("v_p2pool", "v_xvb"),
    "1h": ("v_p2pool_1h", "v_xvb_1h"),
    "12h": ("v_p2pool_12h", "v_xvb_12h"),
    "24h": ("v_p2pool_24h", "v_xvb_24h"),
}

# --- Donation Tier Configuration ---
# Hashrate thresholds (H/s) for XMRvsBeast donation tiers.
# Reference: Official XvB rules (Mega=1M, Whale=100k, VIP=10k, Donor=1k)
TIER_DEFAULTS = {
    "donor_mega": 1_000_000,
    "donor_whale": 100_000,
    "donor_vip": 10_000,
    "donor": 1_000,
}

# Allow runtime configuration override via environment variable (injected via .env)
env_tiers = os.environ.get("TIER_CONFIG")
if env_tiers and env_tiers.strip() and env_tiers != "''":
    try:
        custom_tiers = json.loads(env_tiers.strip("'"))
        if isinstance(custom_tiers, dict):
            TIER_DEFAULTS = custom_tiers
    except json.JSONDecodeError:
        pass

# --- P2Pool Protocol Constants ---
SECOND_PER_BLOCK_MAIN = 120  # Monero Target block time in seconds
