#!/usr/bin/env bash
# The file-budget ratchet gate (#1105 Phase 0): stop the biggest files in the repo from getting
# any bigger, without demanding anyone rewrite them today. Two rules:
#
#   1. A candidate file (tracked, or untracked and not gitignored — #1486) over the 400-line
#      target must record a ceiling in docs/dev/file-budget.tsv; over 800 the refusal names the
#      hard ceiling instead.
#   2. An existing offender (already over 400 when this gate landed, or added to the budget
#      since) gets its CURRENT line count recorded in docs/dev/file-budget.tsv as a personal
#      ceiling. A PR may not grow that file past its recorded ceiling. Ceilings only ever go
#      DOWN — this script rejects any budget edit that raises one (checked against the base
#      branch, $BASE_REF below) — and a file that shrinks back to <=400 must drop its entry.
#      One row is exempt from the "only DOWN" half, because it measures work remaining rather
#      than a file: monotonic_exempt() carries the reasoning.
#
# Exemptions are enumerated by path/glob in is_exempt() below, each with its own reason —
# generated code, vendored files, data/config, and prose docs. The generated root `pithead` is
# git-ignored, while its tracked lib/pithead/*.sh sources remain candidates. Binary files are
# detected generically (grep -I), not listed.
#
# Run `--self-test` first (fixtures for every failure mode, including the empty-enumeration
# guard); `--generate` reprints the budget for every current non-exempt offender, for seeding or
# refreshing the file by hand — it never writes the file itself and never lowers the bar for you.
set -euo pipefail

TARGET_LINES=400
HARD_CEILING=800
BUDGET_FILE="docs/dev/file-budget.tsv"

# The branch this PR ratchets against: `develop`, the one integration branch (the appliance twin
# it once had to detect was retired into it on 2026-09-06). The remote ref first, then the bare
# local name; if neither resolves the monotonic check is skipped with a loud note.
resolve_base_ref() {
    local dev
    for dev in origin/develop develop; do
        if git rev-parse -q --verify "$dev" >/dev/null 2>&1; then
            echo "$dev"
            return 0
        fi
    done
    echo ""
}

# A broken enumeration and a genuinely clean tree both read as "zero hits" — refuse to treat an
# empty candidate list as success. Mirrors lint-topology-classes.sh's own guard.
enforce_nonempty_enumeration() {
    if [ "$(git ls-files | wc -l)" -eq 0 ]; then
        echo "FATAL: git ls-files enumerated zero tracked files. A broken enumeration and a" >&2
        echo "clean tree both scan zero hits — refusing to report either as success." >&2
        return 1
    fi
    return 0
}

# --- exemptions, one glob per reason (case pattern matching: '*' matches '/' too) ---------------
is_exempt() {
    case "$1" in
    # Generated protobuf/gRPC stubs — regenerated by a documented docker command
    # (client/tari/Readme.md), never hand-edited.
    dashboard/mining_dashboard/client/tari/generated/*) return 0 ;;
    *_pb2*) return 0 ;;
    # Vendored .proto interface definitions copied from the upstream Tari project (each file
    # carries Tari's own copyright header) — not authored in this repo.
    dashboard/mining_dashboard/client/tari/proto/*) return 0 ;;
    # Vendored third-party JS (preact/htm/hammer/chartjs-plugin-zoom) — see vendor/README.md.
    dashboard/mining_dashboard/web/static/vendor/*) return 0 ;;
    # Data/config, not source to split: the compose file, dependency lockfiles, JSON
    # fixtures/config (including config.reference.json and test fixtures).
    docker-compose.yml) return 0 ;;
    *.lock) return 0 ;;
    *.json) return 0 ;;
    # Markdown files, including the growing CHANGELOG.md, are reviewed as prose.
    # lint-docs-voice checks authored guides but excludes historical
    # CHANGELOG.md and third-party text; this gate governs source code only.
    *.md) return 0 ;;
    # The XvB delivery study's research material: vendored external source snapshots, captured
    # data, and one-off analysis scripts — not part of the shipped product.
    docs/research/*) return 0 ;;
    # Captured benchmark run data, not source.
    docs/benchmarks/data/*) return 0 ;;
    *) return 1 ;;
    esac
}

# grep -I treats a binary file as non-matching instead of reading it as text; an empty file
# never matches either, but an empty file also never trips a line-count ceiling, so folding the
# two together is safe. Skips images and other binary blobs generically, no path list needed.
is_binary_or_empty() {
    ! LC_ALL=C grep -Iq . "$1" 2>/dev/null
}

# Count lines by record, not by trailing newline (`wc -l` undercounts a file with no final
# newline by one — exactly the off-by-one a mutation proof would otherwise hide).
count_lines() {
    awk 'END { print NR + 0 }' "$1" 2>/dev/null || echo 0
}

# Every tracked OR untracked-but-not-gitignored, non-exempt, non-binary file: "path<TAB>lines",
# one per line. `git ls-files` alone only lists the INDEX — a new file sits invisible right up
# until `git add`, which is exactly the moment a budget gate exists to catch it (#1486). Union in
# `--others --exclude-standard` (untracked, honoring .gitignore) so the working tree, not the
# index, is what gets measured; the two lists are disjoint (`--others` never repeats a tracked
# path) so no dedup is needed.
list_candidates() {
    local f
    {
        git ls-files
        git ls-files --others --exclude-standard
    } | while IFS= read -r f; do
        [ -f "$f" ] || continue
        is_exempt "$f" && continue
        is_binary_or_empty "$f" && continue
        printf '%s\t%s\n' "$f" "$(count_lines "$f")"
    done
}

# Parse a budget file (path<TAB>ceiling, '#' comments and blank lines skipped) from stdin.
parse_budget() {
    grep -vE '^[[:space:]]*(#|$)' | awk -F'\t' 'NF==2 {print $1"\t"$2}'
}

# --- the gate itself --------------------------------------------------------------------------
run_gate() {
    local fail=0 path lines ceiling budget_lines
    enforce_nonempty_enumeration || return 1

    budget_lines=$([ -f "$BUDGET_FILE" ] && parse_budget <"$BUDGET_FILE" || true)

    local candidates
    candidates=$(list_candidates)
    if [ -z "$candidates" ]; then
        echo "FATAL: the candidate scan (git ls-files, minus exemptions/binaries) returned zero" >&2
        echo "files. That is never a legitimately clean result for this tree — refusing to pass." >&2
        return 1
    fi

    while IFS=$'\t' read -r path lines; do
        [ -n "$path" ] || continue
        ceiling=$(printf '%s\n' "$budget_lines" | awk -F'\t' -v p="$path" '$1==p {print $2; exit}')
        if [ -n "$ceiling" ]; then
            if [ "$lines" -gt "$ceiling" ]; then
                echo "file-budget: FAIL — $path is $lines lines, over its recorded ceiling of $ceiling ($BUDGET_FILE)."
                fail=1
            elif [ "$lines" -le "$TARGET_LINES" ]; then
                echo "file-budget: FAIL — $path is $lines lines (<= $TARGET_LINES target) but still has a" \
                    "$BUDGET_FILE entry (ceiling $ceiling). Remove the entry."
                fail=1
            fi
        elif [ "$lines" -gt "$HARD_CEILING" ]; then
            echo "file-budget: FAIL — $path is $lines lines, over the hard ceiling of $HARD_CEILING for a" \
                "new/unbudgeted file (target: $TARGET_LINES)."
            fail=1
        elif [ "$lines" -gt "$TARGET_LINES" ]; then
            # The other half of the same rule: an entry IFF over target. --generate has always
            # emitted exactly this set (`awk '$2 > t'`); the gate now refuses what it would write.
            echo "file-budget: FAIL — $path is $lines lines (> $TARGET_LINES target) but has no" \
                "$BUDGET_FILE entry. Add one: scripts/lint/lint-file-budget.sh --generate."
            fail=1
        fi
    done <<<"$candidates"

    # Every budget entry must name a real, currently-exempt-free, over-target file — a stale
    # entry (deleted, renamed, or exempted since) hides drift instead of proving anything.
    while IFS=$'\t' read -r path ceiling; do
        [ -n "$path" ] || continue
        if [ ! -f "$path" ] || is_exempt "$path"; then
            echo "file-budget: FAIL — $BUDGET_FILE lists '$path', which no longer exists (or is now" \
                "exempt). Remove the entry."
            fail=1
        fi
    done <<<"$budget_lines"

    check_monotonic || fail=1

    if [ "$fail" -ne 0 ]; then
        echo "See CONTRIBUTING.md — file budget gate."
        return 1
    fi
    echo "file budget OK — every over-target file has a ceiling, none grew past it, $BUDGET_FILE is monotonic."
    return 0
}

# The one row whose ceiling may RISE, and why that is not a loosened ratchet (#1464).
#
# lib/pithead/99-remainder.sh is not a file anyone writes. It is whatever of the generated
# `pithead` artifact #1105 Phase 2 has not split out yet, so its ceiling measures work
# REMAINING, not the size of a source file. Routing generated-artifact growth through a ratcheting
# source row created a hard freeze, because no value of the row passed — run_gate refused the
# growth and check_monotonic refused the raise.
#
# What kept it honest is what was NOT changed for it: run_gate's `lines > ceiling` rule is
# untouched, so a PR that grows the artifact must still record the new count, and the row stayed a
# per-PR measurement rather than a ceiling nobody reads. Every Phase 2 slice cut LOWERED it — the
# progress signal the row existed for. Keep this list to rows with that property; a row naming a
# real source file does not have it.
#
# THE ROW HAS RETIRED, and not by reaching the target: Phase 2 split the remainder out completely
# (#1105 P13), so lib/pithead/99-remainder.sh was deleted at 949 lines and no row in
# docs/dev/file-budget.tsv names that path. The arm below therefore matches nothing. Before
# removing it: lint-file-budget-selftest.sh exercises monotonic_exempt() against a synthetic repo
# of its own, and as that self-test records, the plausible mistake here is not deleting this arm
# but widening it to lib/pithead/*. The reasoning above is what governs whether a future row
# earns the same treatment.
monotonic_exempt() {
    case "$1" in
    lib/pithead/99-remainder.sh) return 0 ;;
    *) return 1 ;;
    esac
}

# Ceilings only ever go down. Compare the working-tree budget against the base branch's: any
# path present in both whose ceiling ROSE is a rejected edit, and any path with NO row on the
# base ref (a first appearance) must record the file's real count rather than reserve headroom
# under it — the same "a rise must record, not reserve" reasoning #1464 gave the one exempt row,
# applied to the row's very first line instead of a later raise (#1470).
check_monotonic() {
    local base old_lines new_lines fail=0 path old_ceiling new_ceiling actual
    base=$(resolve_base_ref)
    if [ -z "$base" ]; then
        # It DID happen in CI — on every pull_request run, until lint-surfaces was given
        # fetch-depth: 0 (#1452, #1608). A depth-1 checkout resolves none of the four candidates,
        # so the ratchet skipped here while the gate went on to print "file budget OK".
        #
        # In CI that is a misconfigured job, never a clean tree, so there it is FATAL (#1739). A
        # stderr NOTE inside a job whose other output is voluminous is not a signal anyone reads,
        # so without this arm the ratchet un-arms silently the moment fetch-depth: 0 is lost again
        # — a reflow, a checkout-action bump that changes defaults, a copied job block — and the
        # run that skipped is indistinguishable from a run that checked. Outside CI the NOTE
        # stays: a local checkout legitimately may not carry the base branch refs.
        if [ "${GITHUB_ACTIONS:-}" = true ]; then
            echo "file-budget: FAIL — no base ref (origin/develop or develop) resolvable under" \
                "GITHUB_ACTIONS. The monotonic-ceiling check cannot" \
                "run, and a job that resolves no base ref at all is misconfigured rather than" \
                "clean: restore fetch-depth: 0 on this job (#1452, #1739)."
            return 1
        fi
        echo "file-budget: NOTE — no base ref (origin/develop or develop) resolvable; skipping" \
            "the monotonic-ceiling check. A checkout without the base" \
            "branch refs does this; in CI it means the job has lost its fetch-depth: 0 (#1452)." >&2
        return 0
    fi
    [ -f "$BUDGET_FILE" ] || return 0
    old_lines=$(git show "$base:$BUDGET_FILE" 2>/dev/null | parse_budget || true)
    new_lines=$(parse_budget <"$BUDGET_FILE")

    # One pass over the working-tree rows: a path with no row on $base is a first appearance
    # (#1470), not a raise — it must record the file's real count rather than reserve headroom
    # above it, or nothing mechanical would object again until the file actually grew into it.
    # count_lines is the gate's own counter (not wc -l, which undercounts a file with no
    # trailing newline) and falls back to 0 when the path can't be read, so a deleted or
    # unreadable path mismatches any ceiling and fails closed rather than passing.
    # The complement of that case is #1375's construct, and it is unchecked BY CONSTRUCTION: a
    # path with a row on $base and none here is never visited by this loop at all. It stays safe
    # only because run_gate has already FAILed both of the other ways a path could go missing --
    # an over-target file with no row (its own arm), and a row naming a file that is gone or now
    # exempt (the loop above this one). So a base row absent here can only mean the file shrank
    # to <= TARGET_LINES: the sanctioned removal. That argument leans on run_gate's candidate set
    # being the WHOLE tree (list_candidates), never a diff -- narrow it to changed files and this
    # skip fails open again, silently, because nothing here would change. #1430; the self-test
    # covers the legitimate-removal PASS beside the still-listed-but-shrunk FAIL.
    while IFS=$'\t' read -r path new_ceiling; do
        [ -n "$path" ] || continue
        old_ceiling=$(printf '%s\n' "$old_lines" | awk -F'\t' -v p="$path" '$1==p {print $2; exit}')
        if [ -z "$old_ceiling" ]; then
            actual=$(count_lines "$path")
            if [ "$new_ceiling" != "$actual" ]; then
                echo "file-budget: FAIL — $BUDGET_FILE adds $path as a new row at ceiling" \
                    "$new_ceiling, but the file is $actual lines. A row's first appearance must" \
                    "record the real count, not reserve headroom."
                fail=1
            fi
            continue
        fi
        if [ "$new_ceiling" -gt "$old_ceiling" ]; then
            if monotonic_exempt "$path"; then
                # A rise must RECORD the artifact, not grant it headroom. Without this the
                # exemption would let one PR set the row to any number it liked, and nothing
                # mechanical would object again until the file actually reached it — which
                # would retire the per-PR measurement while still reading as a ratchet.
                actual=$(count_lines "$path")
                if [ "$new_ceiling" != "$actual" ]; then
                    echo "file-budget: FAIL — $BUDGET_FILE raises $path's ceiling to $new_ceiling," \
                        "but the file is $actual lines. That row records the un-split remainder, so a" \
                        "rise must state the real count, not reserve headroom."
                    fail=1
                    continue
                fi
                echo "file-budget: NOTE — $path's ceiling rises from $old_ceiling to $new_ceiling," \
                    "matching the file. That row records the un-split remainder of the generated" \
                    "pithead artifact, so it tracks it both ways (#1464). Every Phase 2 cut lowers" \
                    "it." >&2
                continue
            fi
            echo "file-budget: FAIL — $BUDGET_FILE raises $path's ceiling from $old_ceiling to" \
                "$new_ceiling. Ceilings only go down."
            fail=1
        fi
    done <<<"$new_lines"

    return "$fail"
}

# Reprint the budget the current tree implies (every non-exempt file over target). Never writes
# the file — review the diff and commit it by hand, same as any other ratchet edit.
generate_budget() {
    printf '%s\n' \
        '# Generated by scripts/lint/lint-file-budget.sh --generate. See this script header for the' \
        '# target/ceiling rationale and CONTRIBUTING.md for the gate.'
    printf '# path<TAB>ceiling-in-lines. Ceilings only ever go down; a file at or below %s lines drops its entry.\n' \
        "$TARGET_LINES"
    list_candidates | awk -F'\t' -v t="$TARGET_LINES" '$2 > t {print}' | sort
}

# The fixtures live in lint-file-budget-selftest.sh, which SOURCES this file for the functions
# above (#1464 — this script sat at a ceiling equal to its own length, and its own header rule
# says a file back under the target drops its entry, so the split is the documented remedy).
# Sourcing must therefore define everything and run nothing: without this guard, `source` would
# fall straight into the dispatch below and run the gate against whatever directory the caller
# happened to be in. Executing this script directly dispatches exactly as it always did.
if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
    return 0
fi

case "${1:-}" in
--self-test)
    # Resolve the link before taking the dirname: through a symlink, `dirname "$0"` gives the
    # LINK's directory, so the exec misses and the gate exits 127 — a mis-typed failure rather
    # than a self-test verdict. No call site symlinks this today (the Makefile and CI both run
    # the tracked file), so this is closing a hole rather than fixing a live break. There is
    # deliberately no fixture for it: a case that ran --self-test through a symlink would
    # re-enter the self-test and recurse.
    exec bash "$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")/lint-file-budget-selftest.sh"
    ;;
--generate)
    generate_budget
    exit 0
    ;;
"")
    run_gate
    exit $?
    ;;
*)
    echo "usage: $0 [--self-test|--generate]" >&2
    exit 2
    ;;
esac
